highlighter: pygments
github: site.github.project_title
markdown: kramdown
krandom:
  input: GFM
encoding: UTF-8

#markdown: maruku
#markdown: redcarpet
#encoding: "utf-8"
#markdown_ext: "markdown,md"
